name: Snyk AIML Vulnerability Scan & HTML Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snyk_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies for HTML conversion
        run: |
          python -m pip install --upgrade pip
          pip install json2html

      - name: Install Snyk
        run: npm install -g snyk

      - name: Run Snyk to scan for vulnerabilities in source folder
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk auth $SNYK_TOKEN
          snyk test source --json > snyk_report.json

      - name: Convert Snyk JSON report to HTML
        run: |
          python -c '
import json
from json2html import json2html
with open('snyk_report.json') as f:
    data = json.load(f)
with open('snyk_report.html', 'w') as f:
    f.write(json2html.convert(json=data))
'

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-html-report
          path: snyk_report.html
